### ISSUE TITLE
电信手机号无法注册啊

### ISSUE THREAD

**Issue by tianshaokai** [motianhuo/wechat#14]
我的手机号是电信手机号，发送验证码一直没有收到验证码啊，

**Comment by motianhuo** [comment]
Hi, 谢谢关注，因为短信接口会产生费用，So，Demo将短信下发接口给屏蔽了，不影响正常注册登录

**Comment by tianshaokai** [comment]
那我怎么才能 注册帐号啊，我想看看你的项目呢

**Comment by tianshaokai** [comment]
能不能说一下你的QQ联系方式，想和你学习一下关于视频的这一块，有几个问题想问问你可以吗？

**Comment by tianshaokai** [comment]
能否把web 端也开源一下啊，我自己搭建一个web 端，这样我弄一个测试帐号，就方便多了

**Comment by motianhuo** [comment]
帐号名和密码正常注册，验证码随便输入4位数字， 你加这个群吧：476988719，关注这个项目的都在这里面
