### ISSUE TITLE
close weChat

### ISSUE THREAD

**Issue by bcapd7363q** [motianhuo/wechat#59]
[close weChat](https://restofworld.org/2022/handwritten-wechat-apology-letters/?utm-source=sharing)

# WeChat users are handwriting apologies to get their banned accounts back
- The Tencent app is so essential to life in China that banned users will go to great lengths to be reinstated.

**Comment by 1145906886** [comment]
明天你好这是来自QQ邮箱的假期自动回复邮件。 
  
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by bcapd7363q** [comment]
明天你好这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

___
Hi, I am currently on vacation and cannot reply to your email personally. I will get back to you as soon as possible after the holiday.
